"""add_video_url_to_video_scripts

Revision ID: 9130f914b5a1
Revises: 24177c6ec161
Create Date: 2025-06-21 15:52:48.132983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9130f914b5a1'
down_revision: Union[str, None] = '24177c6ec161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_scripts', sa.Column('video_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_scripts', 'video_url')
    # ### end Alembic commands ###
