"""add cover_image to video_scripts

Revision ID: add_cover_image_to_video_scripts
Revises: 9130f914b5a1
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_cover_image_to_video_scripts'
down_revision = '9130f914b5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_scripts', sa.Column('cover_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_scripts', 'cover_image')
    # ### end Alembic commands ### 